actions:
  post:
    setupibus: "[[ ! -z {{@@ env['DISPLAY'] @@}} ]] && ibus-setup"
    mpdsv: systemctl --user enable mpd.service
    xdgdir: mkdir -p ~/Projects ~/Pictures/Screenshots ~/Music/lyrics
config:
  backup: false
  banner: false
  create: true
  keepdot: true
  showdiff: true
  check_version: true
  dotpath: ~/.dots
variables:
  cfg: home/.config
dynvariables:
  ffcss: fd -t d .default-release ~/.mozilla/firefox
dotfiles:
  d_home:
    src: home
    dst: ~
    link: link_children
    instignore:
      - ".config"
      - ".local"
      - ".xdman"
      - "firefox"
  d_config:
    src: "{{@@ cfg @@}}"
    dst: ~/.config
    link: link_children
    instignore:
      - "BetterDiscord"
      - "Caprine"
      - "gh"
      - "mpd"
      - "qt5ct"
      - "Thunar"
      - "viewnior"
      - "ibus-bamboo"
  BD_plugins_and_themes:
    src: "{{@@ cfg @@}}/BetterDiscord"
    dst: ~/.config/BetterDiscord
    link: link_children
    instignore:
      - "data"
  BD_data:
    src: "{{@@ cfg @@}}/BetterDiscord/data"
    dst: ~/.config/BetterDiscord/data
    link: link_children
  Caprine:
    src: "{{@@ cfg @@}}/Caprine"
    dst: ~/.config/Caprine
    link: link_children
  ibus_bamboo:
    src: "{{@@ cfg @@}}/ibus-bamboo"
    dst: ~/.config/ibus-bamboo
    link: absolute
    actions:
      - setupibus
  gh:
    src: "{{@@ cfg @@}}/gh"
    dst: ~/.config/gh
    link: link_children
  mpd:
    src: "{{@@ cfg @@}}/mpd"
    dst: ~/.config/mpd
    link: link_children
  qt5ct:
    src: "{{@@ cfg @@}}/qt5ct"
    dst: ~/.config/qt5ct
    link: link_children
  thunar:
    src: "{{@@ cfg @@}}/Thunar"
    dst: ~/.config/Thunar
    link: link_children
  viewnior:
    src: "{{@@ cfg @@}}/viewnior"
    dst: ~/.config/viewnior
    link: link_children
  Xdman:
    src: home/.xdman
    dst: ~/.xdman
    link: link_children
  d_ffchrome:
    src: home/firefox
    dst: "{{@@ ffcss @@}}/chrome"
    link: absolute
  d_local:
    src: home/.local
    dst: ~/.local
    link: link_children
    instignore:
      - "share"
  d_localbin:
    src: home/.local/share/bin
    dst: ~/.local/share/bin
    link: absolute
profiles:
  Archie:
    dotfiles:
      - ALL
    actions:
      - mpdsv
      - xdgdir
