actions:
  post:
    ibussetup: >-
      if [[ {{@@ env['DISPLAY'] @@}} == ":*" ]]; then
        ibus-setup
      fi
    dircreate: >-
      mkdir -p ~/Documents/Projects ~/Pictures/Screenshots ~/Music/lyrics
      mkdir -p ~/.local/share/ly ~/.local/share/themes
config:
  backup: false
  banner: false
  create: true
  keepdot: true
  showdiff: true
  check_version: true
  dotpath: home
dynvariables:
  ffcss: >-
    if [[ -d ~/.mozilla/firefox ]]; then
      find ~/.mozilla/firefox/ -type d -name "*default-release"
    fi
  zencss: >-
    if [[ -d ~/.zen ]]; then
      find ~/.zen/ -type d -name "*Default (alpha)"
    fi
dotfiles:
  home:
    src: .
    dst: '~'
    link: link_children
    instignore:
    - .config
    - .local
    - .xdman
    - bin
    - browser
  config:
    src: .config
    dst: ~/.config
    link: link_children
    instignore:
    - aura
    - Caprine
    - gh
    - ibus-bamboo
    - irssi
    - Kvantum
    - lazygit
    - mpd
    - ncmpcpp
    - qBittorrent
    - qt5ct
    - Thunar
    - viewnior
    - systemd
    - simplescreenrecorder
  local_share:
    src: .local/share
    dst: ~/.local/share
    link: link_children
    instignore:
    - icons
    - zoxide
  aura:
    src: .config/aura
    dst: ~/.config/aura
    link: link_children
  Caprine:
    src: .config/Caprine
    dst: ~/.config/Caprine
    link: link_children
  gh:
    src: .config/gh
    dst: ~/.config/gh
    link: link_children
  ibus-bamboo:
    src: .config/ibus-bamboo
    dst: ~/.config/ibus-bamboo
    link: absolute
    actions:
    - ibussetup
  irssi:
    src: .config/irssi
    dst: ~/.config/irssi
    link: link_children
  icons:
    src: .local/share/icons/default
    dst: ~/.local/share/icons/default
    link: link_children
  Kvantum:
    src: .config/Kvantum
    dst: ~/.config/Kvantum
    link: link_children
  lazygit:
    src: .config/lazygit
    dst: ~/.config/lazygit
    link: link_children
  mpd:
    src: .config/mpd
    dst: ~/.config/mpd
    link: link_children
  ncmpcpp:
    src: .config/ncmpcpp
    dst: ~/.config/ncmpcpp
    link: link_children
  qBittorrent:
    src: .config/qBittorrent
    dst: ~/.config/qBittorrent
    link: link_children
  qt5ct:
    src: .config/qt5ct
    dst: ~/.config/qt5ct
    link: link_children
  simplescreenrecorder:
    src: .config/simplescreenrecorder
    dst: ~/.config/simplescreenrecorder
    link: link_children
  systemd:
    src: .config/systemd
    dst: ~/.config/systemd
    link: link_children
  Thunar:
    src: .config/Thunar
    dst: ~/.config/Thunar
    link: link_children
  viewnior:
    src: .config/viewnior
    dst: ~/.config/viewnior
    link: link_children
  xdman:
    src: .xdman
    dst: ~/.xdman
    link: link_children
  zoxide:
    src: .local/share/zoxide
    dst: ~/.local/share/zoxide
    link: link_children
  ff_chrome:
    src: browser/firefox
    dst: '{{@@ ffcss @@}}/chrome'
    link: absolute
  zen_chrome:
    src: browser/zen/userChrome.css
    dst: '{{@@ zencss @@}}/chrome/userChrome.css'
    link: absolute
profiles:
  Archie:
    dotfiles:
    - ALL
    actions:
    - dircreate
