actions:
  post:
    fcitxsetup: >-
      if [[ {{@@ env['DISPLAY'] @@}} == ":*" ]]; then
        fcitx5-configtool
      fi
    dircreate: >-
      mkdir -p ~/Projects ~/.local/share/themes;
      mkdir -p ~/Pictures/Screenshots ~/Music/lyrics;
config:
  backup: false
  banner: false
  create: true
  keepdot: true
  showdiff: true
  check_version: true
  dotpath: home
dynvariables:
  ffcss: >-
    if [[ -d ~/.mozilla/firefox ]]; then
      find ~/.mozilla/firefox/ -type d -name "*default-release"
    fi
dotfiles:
  home:
    src: .
    dst: "~"
    link: link_children
    instignore:
      - .config
      - .local
      - bin
      - browser
  config:
    src: .config
    dst: ~/.config
    link: link_children
    instignore:
      - aura
      - Caprine
      - fcitx5
      - gh
      - ibus-bamboo
      - irssi
      - Kvantum
      - lazygit
      - mpd
      - ncmpcpp
      - qBittorrent
      - qt6ct
      - Thunar
      - viewnior
      - systemd
      - starship.toml
  local_share:
    src: .local/share
    dst: ~/.local/share
    link: link_children
    instignore:
      - icons
      - zoxide
  aura:
    src: .config/aura
    dst: ~/.config/aura
    link: link_children
  Caprine:
    src: .config/Caprine
    dst: ~/.config/Caprine
    link: link_children
  fcitx5:
    src: .config/fcitx5
    dst: ~/.config/fcitx5
    link: link_children
    actions:
      - fcitxsetup
  gh:
    src: .config/gh
    dst: ~/.config/gh
    link: link_children
  irssi:
    src: .config/irssi
    dst: ~/.config/irssi
    link: link_children
  icons:
    src: .local/share/icons/default
    dst: ~/.local/share/icons/default
    link: link_children
  Kvantum:
    src: .config/Kvantum
    dst: ~/.config/Kvantum
    link: link_children
  lazygit:
    src: .config/lazygit
    dst: ~/.config/lazygit
    link: link_children
  mpd:
    src: .config/mpd
    dst: ~/.config/mpd
    link: link_children
  ncmpcpp:
    src: .config/ncmpcpp
    dst: ~/.config/ncmpcpp
    link: link_children
  qBittorrent:
    src: .config/qBittorrent
    dst: ~/.config/qBittorrent
    link: link_children
  qt5ct:
    src: .config/qt6ct
    dst: ~/.config/qt6ct
    link: link_children
  systemd:
    src: .config/systemd
    dst: ~/.config/systemd
    link: link_children
  Thunar:
    src: .config/Thunar
    dst: ~/.config/Thunar
    link: link_children
  viewnior:
    src: .config/viewnior
    dst: ~/.config/viewnior
    link: link_children
  zoxide:
    src: .local/share/zoxide
    dst: ~/.local/share/zoxide
    link: link_children
  ff_chrome:
    src: browser/firefox
    dst: "{{@@ ffcss @@}}/chrome"
    link: absolute
profiles:
  Archlinux:
    dotfiles:
      - ALL
    actions:
      - dircreate
