# Mode
Mode="Uinput (Smooth)"
# Input Method
InputMethod=Telex
# Output Charset
OutputCharset=Unicode
# Enable Spell Check
SpellCheck=False
# Enable Macro
EnableMacro=True
# Capitalize Macro
CapitalizeMacro=True
# Double Space to Period (experimental)
DoubleSpaceToPeriod=False
# Auto Restore Keys With Invalid Words
AutoNonVnRestore=True
# Use oà, uý (Instead Of òa, úy)
ModernStyle=True
# Allow Type With More Freedom
FreeMarking=True
# Allow dd To Produce đ When Auto Restore Keys With Invalid Words Is On
DdFreeStyle=True
# Fix Uinput Mode With Ack
FixUinputWithAck=True
# Use Lotus Status Icons
UseLotusIcons=True

[ModeMenuKey]
0=Alt+grave

