# Reflector configuration file for the systemd service.
# See "reflector --help" for details.

# Set the output path where the mirrorlist will be saved (--save).
--save /etc/pacman.d/mirrorlist

# Most recently synchronized mirrors
-l 50

# Most fastest synchronized mirrors
-f 50

# Return most mirrors
-n 50

# Countries
-c au,at,br,bg,ca,cn,de,ee,fi,fr,in,no,pl,ru,sg,se,tw,gb,us,vn

--download-timeout 15
