# Reflector configuration file for the systemd service.
# See "reflector --help" for details.

# Set the output path where the mirrorlist will be saved (--save).
--save /etc/pacman.d/mirrorlist

# Return mirrors sync-ed in the last hours
-a 72

# Most recently synchronized mirrors
-l 10

# Most fastest synchronized mirrors
-f 10

# Return most mirrors
-n 10

# Countries
-c vn,sg,tw,hk,cn,ru,au,in,jp,dk,se,no,gb,us 

--download-timeout 30
